name: CauldronInteract
version: 1.2.3
api-version: 1.17
author: VoxCrafter_LP
main: com.voxcrafterlp.cauldroninteract.CauldronInteract
description: A simple plugin which enables dispensers to interact with cauldrons
